# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kergosdyr
tagline:          '개발자의 블로그'
description:      '개발 일상 및 공부한 내용을 기록하는 블로그입니다.'
url:              https://github.com/kergosdyr/kergosdyr.github.io
baseurl:          /

author:
  name:           '전진'
  url:            https://github.com/kergosdyr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
