# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kergosdyr
tagline:          '개발자의 블로그'
description:      '개발 일상을 간단하게 정리하고 있어요'
url:              https://github.com/kergosdyr/kergosdyr.github.io
baseurl:          /

author:
  name:           '전진'
  url:            https://github.com/kergosdyr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
